export const mapData = {
    "AAS Layers": [
        { value: "assets/maps/AlBasrah_AAS_1.png", text: "Al Basrah: AAS v1" },
        { value: "assets/maps/Anvil_AAS_1.png", text: "Anvil: AAS v1" },
        { value: "assets/maps/BelayaPass_AAS_1.png", text: "Belaya Pass: AAS v1" },
        { value: "assets/maps/BelayaPass_AAS_2.png", text: "Belaya Pass: AAS v2" },
        { value: "assets/maps/BelayaPass_AAS_3.png", text: "Belaya Pass: AAS v3" },
        { value: "assets/maps/BlackCoast_AAS_1.png", text: "Black Coast: AAS v1" },
        { value: "assets/maps/BlackCoast_AAS_2.png", text: "Black Coast: AAS v2" },
        { value: "assets/maps/Chora_AAS_1.png", text: "Chora: AAS v1" },
        { value: "assets/maps/Chora_AAS_2.png", text: "Chora: AAS v2" },
        { value: "assets/maps/Chora_AAS_3.png", text: "Chora: AAS v3" },
        { value: "assets/maps/Fallujah_AAS_1.png", text: "Fallujah: AAS v1" },
        { value: "assets/maps/FoolsRoad_AAS_1.png", text: "Fool's Road: AAS v1" },
        { value: "assets/maps/FoolsRoad_AAS_2.png", text: "Fool's Road: AAS v2" },
        { value: "assets/maps/GooseBay_AAS_1.png", text: "Goose Bay: AAS v1" },
        { value: "assets/maps/Gorodok_AAS_1.png", text: "Gorodok: AAS v1" },
        { value: "assets/maps/Harju_AAS_1.png", text: "Harju: AAS v1" },
        { value: "assets/maps/Harju_AAS_2.png", text: "Harju: AAS v2" },
        { value: "assets/maps/Harju_AAS_3.png", text: "Harju: AAS v3" },
        { value: "assets/maps/KamdeshHighlands_AAS_1.png", text: "Kamdesh Highlands: AAS v1" },
        { value: "assets/maps/KohatToi_AAS_1.png", text: "Kohat Toi: AAS v1" },
        { value: "assets/maps/Kokan_AAS_1.png", text: "Kokan: AAS v1" },
        { value: "assets/maps/Kokan_AAS_2.png", text: "Kokan: AAS v2" },
        { value: "assets/maps/LashkarValley_AAS_1.png", text: "Lashkar Valley: AAS v1" },
        { value: "assets/maps/LashkarValey_AAS_2.png", text: "Lashkar Valley: AAS v2" },
        { value: "assets/maps/LogarValley_AAS_1.png", text: "Logar Valley: AAS v1" },
        { value: "assets/maps/Manicougan_AAS_1.png", text: "Manicougan: AAS v1" },
        { value: "assets/maps/Manicougan_AAS_2.png", text: "Manicougan: AAS v2" },
        { value: "assets/maps/Manicougan_AAS_3.png", text: "Manicougan: AAS v3" },
        { value: "assets/maps/Mestia_AAS_1.png", text: "Mestia: AAS v1" },
        { value: "assets/maps/Mestia_AAS_2.png", text: "Mestia: AAS v2" },
        { value: "assets/maps/Mutaha_AAS_1.png", text: "Mutaha: AAS v1" },
        { value: "assets/maps/Mutaha_AAS_2.png", text: "Mutaha: AAS v2" },
        { value: "assets/maps/Narva_AAS_1.png", text: "Narva: AAS v1" },
        { value: "assets/maps/Narva_AAS_2.png", text: "Narva: AAS v2" },
        { value: "assets/maps/Narva_AAS_3.png", text: "Narva: AAS v3" },
        { value: "assets/maps/SanxianIslands_AAS_1.png", text: "Sanxian Islands: AAS v1" },
        { value: "assets/maps/SanxianIslands_AAS_2.png", text: "Sanxian Islands: AAS v2" },
        { value: "assets/maps/SanxianIslands_AAS_3.png", text: "Sanxian Islands: AAS v3" },
        { value: "assets/maps/SumariBala_AAS_1.png", text: "Sumari Bala: AAS v1" },
        { value: "assets/maps/SumariBala_AAS_2.png", text: "Sumari Bala: AAS v2" },
        { value: "assets/maps/SumariBala_AAS_3.png", text: "Sumari Bala: AAS v3" },
        { value: "assets/maps/TalilOutskirts_AAS_1.png", text: "Talil Outskirts: AAS v1" },
        { value: "assets/maps/Yehorivka_AAS_1.png", text: "Yehorivka: AAS v1" },
        { value: "assets/maps/Yehorivka_AAS_2.png", text: "Yehorivka: AAS v2" }
    ],
    "Skirmish Layers": [
        { value: "assets/maps/SkirmishLayers/AlBasrah_Skirm_1.png", text: "Al Basrah: Skirmish v1" },
        { value: "assets/maps/SkirmishLayers/AlBasrah_Skirm_2.png", text: "Al Basrah: Skirmish v2" },
        { value: "assets/maps/SkirmishLayers/Anvil_Skirm.png", text: "Anvil: Skirmish" },
        { value: "assets/maps/SkirmishLayers/BelayaPass_Skirm.png", text: "Belaya Pass: Skirmish" },
        { value: "assets/maps/SkirmishLayers/BlackCoast_Skirm.png", text: "Black Coast: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Chora_Skirm.png", text: "Chora: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Fallujah_Skirm_2.png", text: "Fallujah: Skirmish v2" },
        { value: "assets/maps/SkirmishLayers/FoolsRoad_Skirm_1.png", text: "Fool's Road: Skirmish v1" },
        { value: "assets/maps/SkirmishLayers/FoolsRoad_Skirm_2.png", text: "Fool's Road: Skirmish v2" },
        { value: "assets/maps/SkirmishLayers/GooseBay_Skirmish.png", text: "Goose Bay: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Gorodock_Skirm.png", text: "Gorodok: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Harju_Skirm_1.png", text: "Harju: Skirmish v1" },
        { value: "assets/maps/SkirmishLayers/Harju_Skrim_2.png", text: "Harju: Skirmish v2" },
        { value: "assets/maps/SkirmishLayers/KamdeshHighlands_Skirm.png", text: "Kamdesh Highlands: Skirmish" },
        { value: "assets/maps/SkirmishLayers/KohatToi_Skirm.png", text: "Kohat Toi: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Kokan_Skirm.png", text: "Kokan: Skirmish" },
        { value: "assets/maps/SkirmishLayers/LashkarValley_Skirm.png", text: "Lashkar Valley: Skirmish" },
        { value: "assets/maps/SkirmishLayers/LogarValley_Skirm.png", text: "Logar Valley: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Manicougan_Skirm_1.png", text: "Manicougan: Skirmish v1" },
        { value: "assets/maps/SkirmishLayers/Manicougan_Skirm_2.png", text: "Manicougan: Skirmish v2" },
        { value: "assets/maps/SkirmishLayers/Manicougan_Skirm_3.png", text: "Manicougan: Skirmish v3" },
        { value: "assets/maps/SkirmishLayers/Mestia_Skirm.png", text: "Mestia: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Mutaha_Skirm.png", text: "Mutaha: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Narva_Skirm.png", text: "Narva: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Sanxian_Skirm.png", text: "Sanxian: Skirmish" },
        { value: "assets/maps/SkirmishLayers/Skorpo_Skirm.png", text: "Skorpo: Skirmish" },
        { value: "assets/maps/SkirmishLayers/SumariBala_Skirm.png", text: "Sumari Bala: Skirmish" },
        { value: "assets/maps/SkirmishLayers/TalilOutskirts_Skirm_1.png", text: "Talil Outskirts: Skirmish v1" },
        { value: "assets/maps/SkirmishLayers/TalilOutskirts_Skirm_2.png", text: "Talil Outskirts: Skirmish v2" },
        { value: "assets/maps/SkirmishLayers/TalilOutskirts_Skirm_3.png", text: "Talil Outskirts: Skirmish v3" },
        { value: "assets/maps/SkirmishLayers/Yehorivka_Skirmish_1.png", text: "Yehorivka: Skirmish v1" },
        { value: "assets/maps/SkirmishLayers/Yehorivka_Skirmish_2.png", text: "Yehorivka: Skirmish v2" }
    ]
};
